language: haskell
sudo: false

ghc:
  - 7.8
  - '7.10'

install: 
  - cabal install -j --only-dependencies

script:
  - cabal install -j -f portable && haste-compiler/bin/haste-boot --force --initial
